# This file was generated by GoReleaser. DO NOT EDIT.
cask "aether" do
  name "aether"
  desc "Aether CLI — AI-powered cloud development"
  homepage "https://runaether.dev"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aether"

  on_macos do
    on_intel do
      url "https://github.com/pranav100000/homebrew-aether/releases/download/v#{version}/aether_darwin_amd64.tar.gz"
      sha256 "a4f7e5958ced4bd2f66e607f72a15c891b3820efda69e770bc1445c030532939"
    end
    on_arm do
      url "https://github.com/pranav100000/homebrew-aether/releases/download/v#{version}/aether_darwin_arm64.tar.gz"
      sha256 "49797994ae06e2a815c9fba06a5b0f51a3a8a4f4b136e342696036793a1f6f57"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pranav100000/homebrew-aether/releases/download/v#{version}/aether_linux_amd64.tar.gz"
      sha256 "d06beed8ff3783411611dea634aa9c1ceb3181fd1962325b75c0cba26573d0b6"
    end
    on_arm do
      url "https://github.com/pranav100000/homebrew-aether/releases/download/v#{version}/aether_linux_arm64.tar.gz"
      sha256 "0ba28ab552c398a598e59bfc907ce6492da15ff5ee6feb2b83a453a77adcf5b6"
    end
  end

  # No zap stanza required
end
